set copyindent
set expandtab
set noswapfile
set nobackup
set number
set shiftround
set shiftwidth=2
set showmode
set showmatch
set softtabstop=2
set tabstop=2
set termencoding=utf-8

autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
autocmd FileType make set noexpandtab

nnoremap <CR> :nohlsearch<CR><CR>

nnoremap <C-Down> :m .+1<CR>==
nnoremap <C-Up> :m .-2<CR>==
inoremap <C-Down> <Esc>:m .+1<CR>==gi
inoremap <C-Up> <Esc>:m .-2<CR>==gi
vnoremap <C-Down> :m '>+1<CR>gv=gv
vnoremap <C-Up> :m '<-2<CR>gv=gv
